version: "3"
services:
    flask-app:
        build: ./flask-app
        ports:
            - "80:5000"
        depends_on:
            - "es"
        networks:
            - elastic
    es:
        image: elasticsearch:7.5.1
        networks:
            - elastic
        environment:
            - discovery.type=single-node
    nginx:
        image: nginx
        volumes:
            - "/home/bynet13/Desktop/foodtrucks/nginx.conf:/etc/nginx/nginx.conf"
            - "/home/bynet13/Desktop/foodtrucks/project/flask-app/static:/usr/share/nginx/html/static"
        networks:
            - elastic
        ports:
            - "81:80"
        depends_on:
            - "es"
networks:
    elastic:
        driver: bridge